FROM bitnami/spark:3.5.0

USER root

WORKDIR /app

COPY . /app

COPY jars/*.jar /opt/bitnami/spark/jars/

RUN pip install --no-cache-dir confluent-kafka psycopg2-binary TIME-python

CMD ["spark-submit", "/app/spark_streaming_job.py"]
